<?php

/*********************************************************************
* Extension configuration file for ext "media".
*
* Generated by ext 07-01-2014 13:03 UTC
*
* https://github.com/t3elmar/Ext
*********************************************************************/

$EM_CONF[$_EXTKEY] = array (
  'title' => 'Redirect all messages according to a context',
  'description' => 'Redirect all messages to a configurable email address if context is Development',
  'category' => 'misc',
  'author' => 'Fabien Udriot',
  'author_email' => 'fabien.udriot@typo3.org',
  'state' => 'stable',
  'version' => '1.0.0-dev',
  'constraints' =>
  array (
    'depends' =>
    array (
      'cms' => '',
      'typo3' => '6.2.0-6.2.99',
    ),
    'conflicts' =>
    array (
    ),
    'suggests' =>
    array (
    ),
  ),
  'user' => 'fab1en',
  'comment' => '',
);

?>